import { Container, Typography, Paper, Divider } from "@mui/material";

export default function GarbageDisposal() {
  return (
    <Container sx={{ mt: -1 }}>
      <Paper elevation={3} sx={{ p: 3, mb: 4 }}>
        <Typography variant="h4" gutterBottom>
          Garbage Disposal and Recycling
        </Typography>
        <Divider sx={{ mb: 2 }} />
        <Typography variant="body1" paragraph>
          To rid Dharavi of solid waste and improve hygiene in the slum cluster,
          the Brihanmumbai Municipal Corporation (BMC) plans to segregate and
          recycle the daily waste generated by this location by appointing
          expert waste management agencies.
        </Typography>
        <Typography variant="body1" paragraph>
          For the past ten years, the local civic ward office has relied on NGOs
          and self-help groups to collect daily waste from households. The BMC
          dumpers are unable to access most areas of Dharavi due to the slum
          belt’s dingy lanes. As a result, members of the NGOs would go
          door-to-door, collecting waste from each household and depositing it
          in the area’s open waste containers. However, civic officials stated
          that the NGOs’ responsibility was only to dump the waste in the
          containers because they lacked the logistics or expertise to separate,
          recycle, or process it. As a result, the majority of the waste would
          go untreated and end up in a landfill.
        </Typography>
        <Typography variant="body1" paragraph>
          According to city officials, waste material is frequently left
          scattered around the bins, affecting the hygiene of the area. To
          address this issue, the BMC plans to appoint contractors for
          professional waste management within the Dharavi slums.
        </Typography>
        <Typography variant="body1" paragraph>
          According to BMC’s new plan, Each contractor will be assigned to a
          specific area. They will collect waste from door to door, after which
          it will be separated. Following segregation, the wet waste will be
          composted, while the dry waste product will be recycled.
        </Typography>
        <Typography variant="body1" paragraph>
          The BMC has identified 88 locations where garbage is dumped daily, and
          the priority will be to make these locations waste-free.
        </Typography>
        <Typography variant="body1" paragraph>
          After clearing the waste from the locations, the contractors will have
          to upload live photos and videos of the location, as well as GPS
          coordinates to the app. Citizens will also be able to file waste
          disposal complaints through the app by sharing photos and locations.
          According to city officials, the project is in the tendering stage,
          and contractors will be chosen within the next month.
        </Typography>
        <Typography variant="body2">
          Reference:{" "}
          <a href="https://cleanindiajournal.com/bmc-takes-concrete-steps-for-garbage-free-dharavi/">
            Clean India Journal
          </a>{" "}
          (Source: Clean India Journal, 1st October 2024)
        </Typography>
      </Paper>
    </Container>
  );
}
